#!/bin/bash

set -o errexit
set -o pipefail

source fdcli

assert() {
    local expected=$(printf "$1")
    local actual="$(cat)"
    diff -u <(echo "$expected") <(echo "$actual") | sed 's/\t/<<TAB>>/g'
}

def() {
    IFS='\n' read -r -d '' ${1} || true;
}

db() {
    printf -- "${!1}"
}

def users <<'END'
id	name	nick
1	some one	somenick
2	some one else	elsenick
END

db users | db_select id | assert '1\n2\n'
db users | db_select id name | assert '1\tsome one\n2\tsome one else\n'

echo ALL GOOD
### TODO
# test db_select
# test db_where
# test db_format
# test db_join
# test db_print (SHOULD ALSO DO REPLACEMENT OF \n and \t)

# test json_to_db (should replace \t and \n)
